version: "3"
services:
  api:
    build: .
    image: beautycounterteam/api:latest
    volumes:
      - ./log:/usr/app/log
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=development
